// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzhdfwxtncwfauebjcyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6aGRmd3h0bmN3ZmF1ZWJqY3l1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NjQ3NzgsImV4cCI6MjA2NzI0MDc3OH0.xZqqUqJHgBup-tuVLEUWf20uv7-qdVCmEd6R8NUBD-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});